# .github/workflows/generate_weekly_report.yml

name: Generate Weekly Report

on:
  workflow_dispatch:
    inputs:
      week_start:
        description: '週の開始曜日を選択してください (例: monday, tuesday, …)'
        required: true
        default: 'friday' 
      target:
        description: 'どの週を生成するか (last_week / this_week)'
        required: true
        default: 'last_week'

permissions:
  contents: write

jobs:
  build-weekly-report:
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 週の範囲 (START_DATE, END_DATE) を計算する
      - name: Calculate week range
        id: date_calc
        run: |
          WEEK_START="${{ github.event.inputs.week_start }}"  # saturday, sunday, …
          TARGET="${{ github.event.inputs.target }}"          # last_week or this_week

          if [ "$TARGET" = "last_week" ]; then
            END_DATE=$(date -d "last $WEEK_START" +'%Y/%m/%d')
          else
            END_DATE=$(date -d "this $WEEK_START" +'%Y/%m/%d')
          fi

          START_DATE=$(date -d "$END_DATE - 6 days" +'%Y/%m/%d')

          echo "START_DATE=$START_DATE" >> $GITHUB_OUTPUT
          echo "END_DATE=$END_DATE" >> $GITHUB_OUTPUT

      # 3. merged フォルダを作成 (マージした中間ファイル置き場)
      - name: Create merged directory
        run: |
          mkdir -p merged

      # 4. 日報ファイルをマージする
      - name: Merge daily reports
        id: merge
        run: |
          START="${{ steps.date_calc.outputs.START_DATE }}"
          END="${{ steps.date_calc.outputs.END_DATE }}"

          SFMT_START=$(echo "$START" | sed 's/\//-/g')
          SFMT_END=$(echo "$END" | sed 's/\//-/g')

          MERGED_FILE="merged/weekly_${SFMT_START}_to_${SFMT_END}.md"
          echo "" > "$MERGED_FILE"

          CUR="$START"
          COUNT=0

          while [ "$(date -d "$CUR" +'%Y/%m/%d')" != "$(date -d "$END + 1 day" +'%Y/%m/%d')" ]; do
            Y=$(date -d "$CUR" +'%Y')
            M=$(date -d "$CUR" +'%m')
            D=$(date -d "$CUR" +'%d')
            PATH_DAILY="${Y}/${M}/${D}.md"

            if [ -f "$PATH_DAILY" ]; then
              echo -e "\n\n---\n# ${Y}/${M}/${D}\n" >> "$MERGED_FILE"
              cat "$PATH_DAILY" >> "$MERGED_FILE"
              COUNT=$((COUNT + 1))
            fi

            CUR=$(date -d "$CUR + 1 day" +'%Y/%m/%d')
          done

          if [ "$COUNT" -eq 0 ]; then
            echo "Error: No daily reports found between $START and $END" >&2
            exit 1
          fi

          echo "Merged $COUNT daily report(s) into $MERGED_FILE"
          echo "MERGED_FILE=$MERGED_FILE" >> $GITHUB_OUTPUT

      # 5. プロンプト文字列を生成 (テンプレート＋マージ済み日報を組み合わせ)
      - name: Build prompt for Gemini
        id: build_prompt
        run: |
          START="${{ steps.date_calc.outputs.START_DATE }}"
          END="${{ steps.date_calc.outputs.END_DATE }}"
          MERGED_FILE="${{ steps.merge.outputs.MERGED_FILE }}"

          # ← テンプレートを .txt で読み込むように変更
          TEMPLATE_CONTENT=$(<weekly_report_template.txt)
          MERGED_CONTENT=$(<"$MERGED_FILE")

          PROMPT="以下のフォーマットに沿って、テキストファイルの内容を要約して週報を作成してください\n\nテンプレート:\n${TEMPLATE_CONTENT}\n\n対象の内容:\n${MERGED_CONTENT}"

          printf '%s' "$PROMPT" > merged/tmp_prompt.txt
          echo "PROMPT_FILE=merged/tmp_prompt.txt" >> $GITHUB_OUTPUT

      # 6. Gemini API を呼び出して週報を生成
      - name: Call Gemini API for weekly report
        id: ai
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          PROMPT_FILE="${{ steps.build_prompt.outputs.PROMPT_FILE }}"
          echo "Using prompt file: $PROMPT_FILE"

          echo "===== Prompt to Gemini ====="
          cat "$PROMPT_FILE"
          echo "============================="

          # JSON ペイロードを作成
          jq -Rn --arg text "$(cat "$PROMPT_FILE")" \
            '{contents:[{parts:[{text:$text}]}]}' > merged/payload.json

          HTTP_RESPONSE=$(curl -s -w "HTTPSTATUS:%{http_code}" -X POST \
            "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${GEMINI_API_KEY}" \
            -H "Content-Type: application/json" \
            --data-binary @merged/payload.json)

          HTTP_BODY=$(echo "$HTTP_RESPONSE" | sed -e 's/HTTPSTATUS\:.*//g')
          HTTP_STATUS=$(echo "$HTTP_RESPONSE" | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')

          echo "HTTP Status: $HTTP_STATUS"
          echo "Response body: $HTTP_BODY"

          if [ "$HTTP_STATUS" -lt 200 ] || [ "$HTTP_STATUS" -ge 300 ]; then
            echo "ERROR: Gemini API returned status $HTTP_STATUS" >&2
            exit 1
          fi

          GENERATED_CONTENT=$(echo "$HTTP_BODY" | jq -r '.candidates[0].content.parts[0].text')

          if [ -z "$GENERATED_CONTENT" ]; then
            echo "ERROR: Gemini API returned empty content" >&2
            exit 1
          fi

          echo "GENERATED_CONTENT<<EOF" >> $GITHUB_OUTPUT
          echo "$GENERATED_CONTENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # 7. 週報ファイルを作成して書き込む（.txt で出力）
      - name: Create weekly report file
        id: write
        run: |
          mkdir -p weekly_report

          SFMT_START=$(echo "${{ steps.date_calc.outputs.START_DATE }}" | sed 's/\//-/g')
          SFMT_END=$(echo "${{ steps.date_calc.outputs.END_DATE }}" | sed 's/\//-/g')

          WEEKLY_FILE="weekly_report/${SFMT_START}to${SFMT_END}.txt"

          cat << 'EOF' > "$WEEKLY_FILE"
          ${{ steps.ai.outputs.GENERATED_CONTENT }}
          EOF

          echo "WEEKLY_FILE=$WEEKLY_FILE" >> $GITHUB_OUTPUT

      # 8. git コミット & プッシュ
      - name: Commit and push weekly report
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

          SFMT_START=$(echo "${{ steps.date_calc.outputs.START_DATE }}" | sed 's/\//-/g')
          SFMT_END=$(echo "${{ steps.date_calc.outputs.END_DATE }}" | sed 's/\//-/g')
          FILE_PATH="weekly_report/${SFMT_START}to${SFMT_END}.txt"

          git add "$FILE_PATH"
          git diff --cached --quiet || git commit -m "Add weekly report: ${SFMT_START} to ${SFMT_END}"
          git push origin main
